### PR TITLE
Deploy scripts

### PR DESCRIPTION
**Pull request by z00sts**

### CODE REVIEW

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!vmfrontend

**Comment by z00sts** [comment]
!vmfrontend

**Comment by z00sts** [comment]
!vmfrontend

**Comment by z00sts** [comment]
!vmfrontend

**Comment by z00sts** [comment]
!vmfrontend

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by z00sts** [comment]
!test

**Comment by sh0ked** [comment]
!test

**Pull request merged**
